In [1]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

downloaded = drive.CreateFile({'id':'1VmQuqGovW_CQgQq67s6HohW_BTTAkRtE'}) # replace the id with id of file you want to access
downloaded.GetContentFile('breastcancer.csv') 




import pandas
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import io
from sklearn.preprocessing import LabelEncoder

Using TensorFlow backend.


In [2]:
dataset = pd.read_csv("breastcancer.csv").values

labelencoder_Y = LabelEncoder()
y_label = labelencoder_Y.fit_transform(dataset[:,1])

X_train, X_test, Y_train, Y_test = train_test_split(dataset[:,2:32], y_label,
                                                    test_size=0.25, random_state=87)
print(X_train.shape)
print(Y_train.shape)


(426, 30)
(426,)


In [3]:
# dataset = np.asarray(dataset)
np.random.seed(155)
my_first_nn = Sequential() # create model
my_first_nn.add(Dense(60, input_dim=30, activation='relu')) # hidden layer
my_first_nn.add(Dense(1, activation='sigmoid')) # output layer
my_first_nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['acc'])
my_first_nn_fitted = my_first_nn.fit(X_train, Y_train, epochs=100,initial_epoch=0)
my_first_nn.summary()
accu3 = my_first_nn.evaluate(X_test, Y_test)

Epoch 1/100
426/426 [==============================] - 0s 691us/step - loss: 78.4022 - acc: 0.6150
Epoch 2/100
426/426 [==============================] - 0s 47us/step - loss: 22.6644 - acc: 0.2559
Epoch 3/100
426/426 [==============================] - 0s 50us/step - loss: 16.2919 - acc: 0.2160
Epoch 4/100
426/426 [==============================] - 0s 46us/step - loss: 11.7683 - acc: 0.1526
Epoch 5/100
426/426 [==============================] - 0s 49us/step - loss: 8.1442 - acc: 0.2746
Epoch 6/100
426/426 [==============================] - 0s 50us/step - loss: 5.4511 - acc: 0.3568
Epoch 7/100
426/426 [==============================] - 0s 49us/step - loss: 3.1924 - acc: 0.4718
Epoch 8/100
426/426 [==============================] - 0s 54us/step - loss: 2.2846 - acc: 0.5845
Epoch 9/100
426/426 [==============================] - 0s 50us/step - loss: 1.7141 - acc: 0.6643
Epoch 10/100
426/426 [==============================] - 0s 60us/step - loss: 1.3918 - acc: 0.7089
Epoch 11/100
426/426 [==

In [4]:
print("Accuracy: " + str(accu3))

Accuracy: [0.2856464688177709, 0.9160839319229126]


In [5]:

#Question 3
print("BEFORE NORMALIZATION")

BEFORE NORMALIZATION


In [6]:
print(dataset[:, 2:32])

[[17.99 10.38 122.8 ... 0.2654 0.4601 0.1189]
 [20.57 17.77 132.9 ... 0.18600000000000003 0.275 0.08902]
 [19.69 21.25 130.0 ... 0.243 0.3613 0.08757999999999999]
 ...
 [16.6 28.08 108.3 ... 0.1418 0.2218 0.0782]
 [20.6 29.33 140.1 ... 0.265 0.4087 0.124]
 [7.76 24.54 47.92 ... 0.0 0.2871 0.07039]]


In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler().fit(dataset[:, 2:32])
dataset[:, 2:32] = sc.transform(dataset[:, 2:32])
print("AFTER NORMALIZATION")
print(dataset[:, 2:32])

AFTER NORMALIZATION
[[1.097063981469984 -2.0733350146975864 1.2699336881399388 ...
  2.2960761275617894 2.750622244124957 1.9370146123781764]
 [1.8298206075464494 -0.35363240824380465 1.6859547105508976 ...
  1.0870842951700284 -0.24388966756667704 0.2811899865404723]
 [1.5798881149312214 0.4561869517642011 1.566503129858642 ...
  1.9550003461313679 1.1522550000669698 0.2013912093916667]
 ...
 [0.7022842488163855 2.0455737991362346 0.6726757846786613 ...
  0.41406869074035757 -1.1045489528286707 -0.318409158424854]
 [1.8383410334310597 2.336457189943708 1.9825241522696004 ...
  2.2899854886076745 1.919083009868069 2.2196352814468607]
 [-1.8084012451820446 1.2217920363694708 -1.8143885057345746 ...
  -1.7450628184932917 -0.048138213587915424 -0.751206692822193]]


In [9]:
X_train, X_test, Y_train, Y_test = train_test_split(dataset[:, 2:32], y_label,
                                                 test_size=0.25, random_state=87)
np.random.seed(155)
my_first_nn = Sequential() # create model
my_first_nn.add(Dense(60, input_dim=30, activation='relu')) # hidden layer
my_first_nn.add(Dense(1, activation='sigmoid')) # output layer
my_first_nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['acc'])
my_first_nn_fitted = my_first_nn.fit(X_train, Y_train, epochs=100,initial_epoch=0)
my_first_nn.summary()
accu4 = my_first_nn.evaluate(X_test, Y_test)

Epoch 1/100
426/426 [==============================] - 0s 234us/step - loss: 0.5282 - acc: 0.7793
Epoch 2/100
426/426 [==============================] - 0s 44us/step - loss: 0.3047 - acc: 0.9437
Epoch 3/100
426/426 [==============================] - 0s 42us/step - loss: 0.2119 - acc: 0.9507
Epoch 4/100
426/426 [==============================] - 0s 44us/step - loss: 0.1678 - acc: 0.9531
Epoch 5/100
426/426 [==============================] - 0s 49us/step - loss: 0.1420 - acc: 0.9624
Epoch 6/100
426/426 [==============================] - 0s 47us/step - loss: 0.1252 - acc: 0.9624
Epoch 7/100
426/426 [==============================] - 0s 47us/step - loss: 0.1136 - acc: 0.9624
Epoch 8/100
426/426 [==============================] - 0s 62us/step - loss: 0.1043 - acc: 0.9624
Epoch 9/100
426/426 [==============================] - 0s 47us/step - loss: 0.0967 - acc: 0.9624
Epoch 10/100
426/426 [==============================] - 0s 42us/step - loss: 0.0905 - acc: 0.9695
Epoch 11/100
426/426 [======

In [10]:
print(my_first_nn.metrics_names)

['loss', 'acc']


In [11]:
print("Accuracy: " + str(accu3))
print("Accuracy After Normalization: " + str(accu4))

Accuracy: [0.2856464688177709, 0.9160839319229126]
Accuracy After Normalization: [0.21503354515229073, 0.9650349617004395]
